version: "3.8"
services:
  uporabniki-service:
    build:
      context: ./UporabnikiService  
    container_name: uporabniki_service
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
    volumes:
      # Only mount database files
      - ./UporabnikiService/test.db:/app/test.db
      - ./UporabnikiService/users.db:/app/users.db
    restart: unless-stopped

  filmi-service:
    build:
      context: ./FilmiService  
    container_name: filmi_service
    ports:
      - "50051:50051"  
    volumes:
      - ./FilmiService/movies.db:/app/movies.db  
    restart: unless-stopped


  