# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import movies_pb2 as movies__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in movies_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovieById = channel.unary_unary(
                '/movies.MovieService/GetMovieById',
                request_serializer=movies__pb2.MovieRequest.SerializeToString,
                response_deserializer=movies__pb2.MovieResponse.FromString,
                _registered_method=True)
        self.SearchMovies = channel.unary_unary(
                '/movies.MovieService/SearchMovies',
                request_serializer=movies__pb2.SearchRequest.SerializeToString,
                response_deserializer=movies__pb2.MovieList.FromString,
                _registered_method=True)


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovieById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovieById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovieById,
                    request_deserializer=movies__pb2.MovieRequest.FromString,
                    response_serializer=movies__pb2.MovieResponse.SerializeToString,
            ),
            'SearchMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMovies,
                    request_deserializer=movies__pb2.SearchRequest.FromString,
                    response_serializer=movies__pb2.MovieList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movies.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movies.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovieById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/GetMovieById',
            movies__pb2.MovieRequest.SerializeToString,
            movies__pb2.MovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movies.MovieService/SearchMovies',
            movies__pb2.SearchRequest.SerializeToString,
            movies__pb2.MovieList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
