# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movies.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'movies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\x12\x06movies\"\x1a\n\x0cMovieRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"l\n\rMovieResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tors\x18\x06 \x03(\t\"2\n\tMovieList\x12%\n\x06movies\x18\x01 \x03(\x0b\x32\x15.movies.MovieResponse2\x85\x01\n\x0cMovieService\x12;\n\x0cGetMovieById\x12\x14.movies.MovieRequest\x1a\x15.movies.MovieResponse\x12\x38\n\x0cSearchMovies\x12\x15.movies.SearchRequest\x1a\x11.movies.MovieListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIEREQUEST']._serialized_start=24
  _globals['_MOVIEREQUEST']._serialized_end=50
  _globals['_SEARCHREQUEST']._serialized_start=52
  _globals['_SEARCHREQUEST']._serialized_end=82
  _globals['_MOVIERESPONSE']._serialized_start=84
  _globals['_MOVIERESPONSE']._serialized_end=192
  _globals['_MOVIELIST']._serialized_start=194
  _globals['_MOVIELIST']._serialized_end=244
  _globals['_MOVIESERVICE']._serialized_start=247
  _globals['_MOVIESERVICE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
